In [3]:
import numpy as np

In [39]:
# Uniform distribution
uniform = np.random.rand(3, 3)
print("🎯 Uniform distribution:\n", uniform)

🎯 Uniform distribution:
 [[0.53799742 0.09610836 0.22409704]
 [0.69456721 0.47778852 0.56808924]
 [0.27326383 0.82070171 0.24666514]]


In [41]:
# Normal distribution
normal = np.random.randn(3, 3)
print("\n📈 Normal distribution:\n", normal)


📈 Normal distribution:
 [[-0.1187919   1.71428348  1.2692846 ]
 [ 0.02802686 -0.20176361 -0.88213825]
 [ 1.27537466  0.17522774  1.1090105 ]]


In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [7]:
np.where(arr > 3)

(array([3, 4], dtype=int64),)

In [11]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [13]:
np.where(arr>5)

(array([], dtype=int64),)

In [67]:
print("Where > 3:", np.where(arr > 3))

Where > 3: (array([3, 4], dtype=int64),)


In [15]:
arr = np.array([1, 2, 3, 4, 5])


In [17]:
np.argmax(arr)

4

In [19]:
np.argmin(arr)

0

In [49]:
print("Max Index:", np.argmax(arr))


Max Index: 4


In [52]:
print("Min Index:", np.argmin(arr))

Min Index: 0


In [21]:
sorted_arr = np.array([1, 3, 5 , 7 ])

In [23]:
np.searchsorted(sorted_arr, 6)

3

In [25]:
np.searchsorted(sorted_arr, 100)

4

In [27]:
np.searchsorted(sorted_arr, 0)

0

In [56]:

print("Insert 6 at index:", np.searchsorted(sorted_arr, 6))

Insert 6 at index: 3


In [60]:
arr = np.array([1, 2, 3, 4, 5])

In [62]:
print("Extract > 3:", np.extract(arr > 3, arr))

Extract > 3: [4 5]


In [71]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [74]:
print("Original:\n", matrix)


Original:
 [[1 2 3]
 [4 5 6]]


In [77]:
print("Transposed:\n", np.transpose(matrix))

Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [80]:
arr = np.array([1, 2, 3, 4, 5])


In [82]:
print("Mean value:", np.mean(arr))

Mean value: 3.0


In [ ]:
## Equal parts split

In [39]:
arr = np.array([1,  2, 3, 4, 5, 6])



np.split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# Split at specific positions

In [41]:
np.split(arr, [1, 4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [94]:
print("Split at Indices:", ) # Split at specific positions 

Split at Indices: [array([1]), array([2, 3, 4]), array([5, 6])]


In [43]:
matrix = np.array([[1,| 2,| 3], 
                  -------------
                   [4,| 5,| 6]])


In [51]:
np.split(matrix, 3, axis=1)   #→ Split columns

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [ ]:
[[1, 2, 3],
 [4, 5, 6]]


In [ ]:
[ [ [1], [4] ],
 
  [ [2], [5] ],
 
  [ [3], [6] ] ]


In [117]:
np.split(matrix, 2, axis=0) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
Original Matrix:
[ [1, 2, 3],
  [4, 5, 6] ]

Split along axis=0 (rows):
→   [1, 2, 3]
     ↓
     [4, 5, 6]

Result:
[
 [[1, 2, 3]],
 [[4, 5, 6]]
]


In [53]:
arr = np.array([3, 1, 4, 2])


In [55]:
print("Sorted Copy:", np.sort(arr))

Sorted Copy: [1 2 3 4]


In [57]:
arr

array([3, 1, 4, 2])

In [59]:
arr.sort()


In [61]:
arr

array([1, 2, 3, 4])

In [138]:
matrix = np.array([[3, 1, 2],
                   [6, 5, 4]])

In [144]:

print("Sorted Rows:\n", np.sort(matrix, axis=1))

Sorted Rows:
 [[1 2 3]
 [4 5 6]]


In [148]:
print("Sorted columns:\n", np.sort(matrix, axis=0))

Sorted columns:
 [[3 1 2]
 [6 5 4]]


In [ ]:
## Concatenates arrays along a specified axis

In [151]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])


In [154]:
print("Vertical Join:\n", np.concatenate((arr1, arr2), axis=0))

Vertical Join:
 [[1 2]
 [3 4]
 [5 6]]


In [156]:
a = np.array([1, 2])
b = np.array([3, 4])


In [158]:
print("Horizontal Join:\n", np.hstack((a, b)))

Horizontal Join:
 [1 2 3 4]


In [165]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])


In [168]:
print("Vertical Stack:\n", np.vstack((arr3, arr4)))

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [ ]:
### Stacks arrays vertically (row-wise)

In [170]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [172]:
# Filter values > 3
print("Filtered > 3:", arr[arr > 3])

Filtered > 3: [4 5 6]


In [174]:
# Filter values between 2 and 6
print("Between 2 and 6:", arr[(arr > 2) & (arr < 6)])

Between 2 and 6: [3 4 5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])




# Create a boolean mask
mask = arr > 3

In [24]:
mask

array([False, False, False,  True,  True,  True])

In [26]:
# Apply the mask to filter the array
filtered = arr[mask]

print("Filtered elements (greater than 3):", filtered)


Filtered elements (greater than 3): [4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [36]:
(arr > 2) & (arr < 6)

array([False, False,  True,  True,  True, False])

In [34]:

arr[(arr > 2) & (arr < 6)]

array([3, 4, 5])

In [41]:
arr[(arr <= 3) | (arr > 5)]

array([1, 2, 3, 6])

In [47]:
# Elements less than or equal to 3 OR greater than 5


arr[(arr <= 3) | (arr > 5)]




array([1, 2, 3, 6])

In [51]:
matrix = np.array([
    [10, 15, 20],
    [25, 30, 35]
])

# Get elements greater than 20
print("Values > 20:", matrix[matrix > 20])


Values > 20: [25 30 35]


In [56]:
scores = np.array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])

In [58]:
# Find students who scored more than 90
high_scores = scores[scores > 90]

In [60]:
print("Students scoring > 90:", high_scores)

Students scoring > 90: [92 95 94]


In [70]:
np.random.randint(0,15)

13

3. Given an array of product prices, filter the ones above ₹500:
   `prices = [250, 499, 520, 310, 800, 999, 450, 720]`



In [87]:
prices = np.array([250, 499, 520, 310, 800, 999, 450, 720])


In [91]:
prices[prices%2==0]

array([250, 520, 310, 800, 450, 720])

In [89]:
prices[prices>500]

array([520, 800, 999, 720])

By mastering filtering with NumPy, you can quickly extract meaningful data from larger datasets — a vital step in data analysis and machine learning pipelines!
